### ISSUE TITLE
Event driver error in Yagi

### ISSUE THREAD

**Issue by lintonv** [rackerlabs/yagi#63]
Traceback (most recent call last):
  File "/usr/bin/yagi-event", line 29, in <module>
    yagi.start_consumers()
  File "/usr/lib/python2.6/site-packages/yagi/__init__.py", line 29, in start_consumers
    yagi.event_worker.start(consumers)
  File "/usr/lib/python2.6/site-packages/yagi/event_worker.py", line 15, in start
    'event_driver'))()
  File "/usr/lib/python2.6/site-packages/yagi/utils.py", line 13, in import_class
    raise Exception("Could not load class %s" % klass_str)
Exception: Could not load class yagi.broker.rabbit.Broker

I keep getting the error above when I try to run the following command -
yagi-event -c yagi.conf

**Comment by Ashwinvalento** [comment]
you need to activate the virtualenv 
# source /opt/stv3/bin/activate 
or you can use the python from the tar
/opt/stv3/bin/python yagi-event -c yagi.conf

**Comment by lamaryan** [comment]
hello,
I have a problem. 
I start HUB in localhost using'
python /root/tmp/google_appengine/dev_appserver.py /root/tmp/pubsubhubbub-read-only/hub/ --port 8080 &'.
And start client webserver in localhost using 
'python /root/tmp/yagi-master/subscriber/callback.py 1111 &'
Then I subscribe to HUB using 'python /root/tmp/yagi-master/subscriber/sub.py 1111 8080'
I got crash:
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/root/tmp/google_appengine/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/root/tmp/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/root/tmp/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/root/tmp/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/root/tmp/google_appengine/lib/webapp2-2.3/webapp2.py", line 1076, in __call__
    handler = self.handler(request, response)
TypeError: __init__() takes at most 2 arguments (3 given)
